### ISSUE TITLE
Review https://dailyhodl.com/2019/07/21/stablecoins-top-10-islands-in-the-whirling-sea-of-crypto/

### ISSUE THREAD

**Issue by abitmore** [bitshares/marketing#13]

**Comment by sschiessl-bcp** [comment]
Contact established, options are being discussed. Likely outcome: Article can't be changed, and the sources were cited correct (CMC did show weird numbers at that time). Discussing possibilities of a follow up.

**Comment by sschiessl-bcp** [comment]
Article can't be changed. Author is currently not looking to do a follow up.
