### ISSUE TITLE
[list BTS] Binance DEX 

### ISSUE THREAD

**Issue by bitcoinsfacil** [bitshares/marketing#35]
Binance Chain is a blockchain developed by Binance and BinanceDEX works on top of this Blockchain. Like BitShares. 

https://docs.binance.org/list_instruction.html

Issue Asset 500 BNB
Propose Asset for DEX listing 5 BNB

If it gets approved by 11 validators:
List Asset 1000 BNB

**Comment by froooze** [comment]
What advantages do you see for BTS? 
The problem with Binance DEX is, that it is still a CEX on blockchain. 

https://coinmarketcap.com/exchanges/binance-dex/

**Comment by sschiessl-bcp** [comment]
You are looking at least at 37500 USD at current BNB price only for the fees. While it would be nice, you would need to

 - do a WP or other to create necessary funds
 - have a gateway commit to it, or operate own gateway

**Comment by bitcoinsfacil** [comment]
Understood, not for this moment
