### ISSUE TITLE
Review https://www.hbg.com/en-us/assetintro/#bts

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/marketing#7]

**Comment by sschiessl-bcp** [comment]
Contacted again.

**Comment by sschiessl-bcp** [comment]
Correction

# 1. Symbol and Name
BTS - Core token of the BitShares Blockchain 

# 2. Project Introduction

The BitShares blockchain is an industrial-grade decentralized platform built for high-performance smart contracts with a focus on the financial technologies sector. Any individual or organization can freely transfer, borrow, trade and create custom tokens on this platform. It also offers a low cost, decentralized, high-performance cryptocurrency exchange, including payment gateways, direct debit and token management platforms, including atomic cross chain swaps.

BitShares invented the MPA (Market Pegged Asset, or Smart Coins), like BitUSD (1 BitUSD= 1 USD), with has at least 1.6 times its value in BTS as collateral backing (at the time of writing, the actual ratio is a blockchain parameter). Smart Coins are set in place that automatically trigger margin calls to guarantee sufficient collateralization. In the process of providing high liquidity in blockchain assets, MPA’s also has the advantage of ensuring stability of value, making it suitable for payment and trading scenario.

The BitShares technology is extended to areas outside finance, such as gaming, music, and social media. BitShares represents the first decentralized autonomous cooperation (DAC), which provides a high level of service quality at a lower cost than traditional centralized entities.

The BitShares blockchain has the fastest transaction confirmation speed, and the largest transaction capacity amongst public blockchains. Stress tests have proven that the BitShares Blockchain can support 3,300 transactions per second (TPS) and a total of 22,000 operations a second, while its potential TPS is 100,000. As a reference, all VISA transactions can be handled by roughly 1800 TPS.

# 3. Distribution

Total Supply: 3.6 billion including approximately 0.9 billion in working budget 
Total in Circulation: approximately 2.7 billion
Token decimal: 5

# 4. Useful Links

Website: https://bitshares.org; https://news.bitshares.org/
Whitepaper: http://bitshares.foundation/whitepaper
Block Explorer: http://bts.ai; https://open-explorer.io; https://bitsharescan.com; http://www.cryptofresh.com;

**Comment by sschiessl-bcp** [comment]
Translated by GBAC

# 1. 标志和名称

BTS-比特股区块链的核心数字货币

# 2. 项目介绍

比特股区块链是一个工业级去中心化平台，专为高性能智能合约而设计，专注于金融技术领域。任何个人或组织都可以在此平台上自由转移，借贷，交易和创建自定义数字货币。比特股还提供低成本，去中心化，高性能的加密货币交换，包括支付网关，直接借记和数字货币管理平台，以及跨链原子互换。

比特股发明了MPA（市场挂钩资产或智能货币），如BitUSD（1 BitUSD = 1 USD），如需借贷智能货币，至少需要以其1.6倍价格的BTS进行担保（该比例为撰写本文时比率，实际比率参考区块链中参数）。智能货币会自动触发追加保证金通知，以保证充分的抵押。在为区块链资产提供高流动性的过程中，MPA还具有确保价值稳定性的优势，使其适用于支付和交易场景。

比特股技术还扩展到了金融领域以外的领域，如游戏，音乐和社交媒体。比特股代表了第一个去中心化自治公司（DAC），它以比传统中心化式实体以更低的成本提供更高水平的服务质量。

比特股区块链具有最快的交易确认速度，以及拥有公链中最大的交易容量。压力测试证明，比特股区块链每秒可以支持3,300次交易（TPS），每秒可以支持22,000次操作，而其潜在的TPS为100,000。作为参考，所有VISA交易的处理速度大约为1800 TPS。比特股区块链是一个工业级去中心化平台，专为高性能智能合约而设计，专注于金融技术领域。任何个人或组织都可以在此平台上自由转移，借贷，交易和创建自定义数字货币。比特股还提供低成本，去中心化，高性能的加密货币交换，包括支付网关，直接借记和数字货币管理平台，以及跨链原子互换。

比特股发明了MPA（市场挂钩资产或智能货币），如BitUSD（1 BitUSD = 1 USD），如需借贷智能货币，至少需要以其1.6倍价格的BTS进行担保（该比例为撰写本文时比率，实际比率参考区块链中参数）。智能货币会自动触发追加保证金通知，以保证充分的抵押。在为区块链资产提供高流动性的过程中，MPA还具有确保价值稳定性的优势，使其适用于支付和交易场景。

比特股技术还扩展到了金融领域以外的领域，如游戏，音乐和社交媒体。比特股代表了第一个去中心化自治公司（DAC），它以比传统中心化式实体以更低的成本提供更高水平的服务质量。

比特股区块链具有最快的交易确认速度，以及拥有公链中最大的交易容量。压力测试证明，比特股区块链每秒可以支持3,300次交易（TPS），每秒可以支持22,000次操作，而其潜在的TPS为100,000。作为参考，所有VISA交易的处理速度大约为1800 TPS。

# 3. 分配

总供应量：36亿，其中包括约9亿的工作预算
流通总额：约27亿
数字货币小数位：5

# 4. 链接

网站: https://bitshares.org https://news.bitshares.org/
白皮书: http://bitshares.foundation/whitepaper
区块浏览器: http://bts.ai; https://open-explorer.io; https://bitsharescan.com; http://www.cryptofresh.com;

**Comment by sschiessl-bcp** [comment]
Sent to Huobi

[hbg_bts_asset_introduction_en.txt](https://github.com/bitshares/marketing/files/3504527/hbg_bts_asset_introduction_en.txt)
[hbg_bts_asset_introduction_zh.txt](https://github.com/bitshares/marketing/files/3504528/hbg_bts_asset_introduction_zh.txt)

**Comment by sschiessl-bcp** [comment]
> Thank you for reaching out to us regarding the asset description.We have updated the official website project according to your documents.
> 
> 
> BTS English version：https://www.huobi.so/en-us/assetintro/#bts
> 
> BTS Chinese version：https://www.huobi.so/zh-cn/assetintro/#bts

**Comment by abitmore** [comment]
@sschiessl-bcp have we put the text somewhere "official" and easy to find, so every 3rd website can link and/or copy & paste ?
